const mongoose = require('mongoose');
const Schema = mongoose.Schema;
/*
MODULE OF CART'S MODEL
MODULE NAME: CART_MODEL
PROGRAMMER: GUO Jialiang 1155124399
VERSION: 1.0 (12 APRIL 2021)
DESCRIBE: a cart item has its own id (generated by the db), user ID, dish ID,
dish name, price of the dish, canteen which the dish belongs to, and quantity
 */
const cartSchema = new Schema({
    userID: {
        type: String,
        required: true
    },
    dishID: {
        type: String,
        required: true
    },
    name: {
        type: String,
        required: true
    },
    price: {
        type: Number,
        required: true
    },
    canteen: {
        type: String,
        required: true
    },
    quantity: {
        type: Number,
        required: true
    }
})
const Cart = mongoose.model('Cart', cartSchema);

module.exports = Cart;
