const mongoose = require('mongoose');
const Schema = mongoose.Schema;
/*
MODULE OF CONTENT'S MODEL
MODULE NAME: CONTENT_MODEL
PROGRAMMER: GUO Jialiang 1155124399
VERSION: 1.2 (14 APRIL 2021)
DESCRIBE: a content item has its ID(generated by the db), details, owner's ID,
user's name, number of likes, dish name, canteen which the dish belongs to,
rating of the dish, and timestamp(in unix timestamp)
 */
const contentSchema = new Schema({
    detail: {
        type: String,
        required: true// to do
    },
    ownID: {
        type: String,
        required: true// to do
    },
    userName: {
        type: String,
        required:true
    },
    likeNum:{
        type: Number,
        required: false,
        default: 0
    },
    canteen: {
        type: String,
        required: true
    },
    dish: {
        type: String,
        required: true
    },
    rating: {
        type: Number,
        required: false,
        default: 5
    },
    avatar: {
        type: String,
        required: false
    }
},{timestamps: true})

const Content = mongoose.model('Content', contentSchema);

module.exports = Content;
