const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Each image has its ID (generated by the db), username, dish name
// canteen, and url of the image
const gallerySchema = new Schema({
    username: {
        type: String,
        required:true,
    },
    dish: {
      type: String,
      required: true
    },
    canteen: {
        type: String,
        required: true
    },
    Image: {
        type: String,
        required: true
    }
})
const Gallery = mongoose.model("Gallery",gallerySchema);

module.exports = Gallery;
