const mongoose = require('mongoose');
const Schema = mongoose.Schema;
/*
MODULE OF GALLERY'S MODEL
MODULE NAME: GALLERY_MODEL
PROGRAMMER: GUO Jialiang 1155124399
VERSION: 1.1 (15 APRIL 2021)
DESCRIBE: Each image has its ID (generated by the db), username, dish name
canteen, and url of the image
 */
const gallerySchema = new Schema({
    username: {
        type: String,
        required:true,
    },
    dish: {
      type: String,
      required: true
    },
    canteen: {
        type: String,
        required: true
    },
    Image: {
        type: String,
        required: true
    }
})
const Gallery = mongoose.model("Gallery",gallerySchema);

module.exports = Gallery;
