const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Each record has its ID (generated by the db), user ID, dish name
// price, canteen, quantity, subtotal, and timestamp (in unix timestamp)
const recordSchema = new Schema({
    userID: {
      type: String,
      required: true
    },
    name: {
        type: String,
        required: true
    },
    price: {
        type: Number,
        required: true
    },
    canteen: {
        type: String,
        required: true
    },
    quantity: {
        type: Number,
        required: true
    },
    subtotal:{
        type: Number,
        required: true
    }
},{timestamps:true})
const Record = mongoose.model('Record', recordSchema);

module.exports = Record;
