const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Each user has its ID (generated by the db), name, password(hash), user type,
// and canteen works in(for managers only)
const userSchema = new Schema({
    name: {
        type: String,
        required:true,
        unique:true
    },
    password: {
        type: String,
        required: true
    },
    type: {
        type: String,
        required: true,
        default: "user"
    },
    canteen: {
        type: String,
        required: false,
        default: ""
    }
})
const User = mongoose.model("User",userSchema);

module.exports = User;
